site_name: Java-Microservice
site_author: Sven Ruppert
google_analytics: ['UA-35462441-4', 'MicroService']


pages:
- Home: index.md

- Configuration:
  - Parameters: configuration/parameter.md
  - Startup/Shutdown Action: configuration/action.md
- Optionals:
  - Admin: configuration/admin.md
  - Command Line Instructions: configuration/cli.md
  - Filesystem: configuration/filesystem.md
  - Index: configuration/index.md
  - Metrics: configuration/metrics.md
  - Service: configuration/service.md
- Projectinfos: projectinfos/index.md
- Additional Infos: additionalinfos/index.md
- About: about.md

theme: united
#markdown_extensions: [fenced_code]
markdown_extensions:
    - toc:
